catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog import views
from catalog.views import contact, ProductListView, ProductDetailView, BlogListView, BlogDetailView, BlogCreateView, \
    BlogUpdateView, BlogDeleteView, ProductCreateView, ProductUpdateView
from main.apps import MainConfig

app_name = MainConfig.name

urlpatterns = [
    path('', ProductListView.as_view(), name='home'),
    path('contacts/', contact, name='contacts'),
    path('product/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product'),
    path('create_product/', ProductCreateView.as_view(), name='create_product'),
    path('edit_product/<int:pk>/', ProductUpdateView.as_view(), name='edit_product'),
    path('blog/', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_article'),
    path('create/', BlogCreateView.as_view(), name='create_article'),
    path('edit/<int:pk>/', BlogUpdateView.as_view(), name='edit_article'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='delete_article'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from django.contrib.auth.views import LoginView, LogoutView

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, generate_new_password, UserConfirmEmailView, \
    UserConfirmationSentView, UserConfirmedView, UserConfirmationFailView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('email_confirmation_sent/', UserConfirmationSentView.as_view(), name='email_confirmation_sent'),
    path('confirm_email/<str:uidb64>/<str:token>/', UserConfirmEmailView.as_view(), name='confirm_email'),
    path('email_confirmed/', UserConfirmedView.as_view(), name='email_confirmed'),
    path('email_confirmation_failed/', UserConfirmationFailView.as_view(), name='email_confirmation_failed'),
    ]

catalog/models.py
from datetime import date

from django.db import models
from django.db.models import SET_DEFAULT, SET_NULL

from config import settings

NULLABLE = {'blank': True, 'null': True}


class Category(models.Model):
    """
    Класс для создания категорий товаров
    """
    category_name = models.CharField(max_length=150, verbose_name='Категория')
    category_description = models.CharField(max_length=150, verbose_name='Описание')

    # is_active = models.BooleanField(default=True, verbose_name='учится')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.category_name}'

    class Meta:
        verbose_name = 'Категория'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Категории'  # Настройка для наименования набора объектов
        ordering = ('category_name',)  # сортировка по наименованию


class Product(models.Model):
    """
    Класс для создания товаров
    """
    VERSION_CHOICES = ((True, 'Опубликован'), (False, 'На модерации'))

    product_name = models.CharField(max_length=150, verbose_name='Наименование')
    product_description = models.CharField(max_length=150, verbose_name='Описание')
    product_preview = models.ImageField(upload_to='catalog/', verbose_name='Превью', **NULLABLE)
    product_category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='Категория')
    product_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    date_creation = models.DateField(auto_now=False, auto_now_add=True, verbose_name='Дата создания')
    date_changing = models.DateField(auto_now=True, auto_now_add=False, verbose_name='Дата последнего изменения')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)
    is_active = models.BooleanField(choices=VERSION_CHOICES, default=False, verbose_name='Текущая версия')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.product_name} {self.product_price}'

    class Meta:
        verbose_name = 'Товар'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Товары'  # Настройка для наименования набора объектов
        ordering = ('product_name',)  # сортировка по наименованию

        permissions = [
            ('set_product_is_active', 'Can change the status of products'),
            ('change_product_description', 'Can change product description'),
            ('change_product_category', 'Can change product category'),
        ]


class Version(models.Model):
    """
    Класс для создания версии товароа
    """
    VERSION_CHOICES = ((True, 'активная'), (False, 'не активная'))

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    version_number = models.IntegerField(default=1, blank=True, verbose_name='Номер версии')
    version_name = models.CharField(max_length=150, verbose_name='Название')
    is_active = models.BooleanField(choices=VERSION_CHOICES, verbose_name='Текущая версия')

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.product} {self.version_number}'

    class Meta:
        verbose_name = 'Версия'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Версии'  # Настройка для наименования набора объектов
        ordering = ('version_number',)  # сортировка по номеру версии


class Blog(models.Model):
    """
    Класс для ведения блога
    """
    blog_title = models.CharField(max_length=150, verbose_name='Заголовок')
    blog_text = models.TextField(verbose_name='Содержимое')
    blog_preview = models.ImageField(upload_to='catalog/', verbose_name='Превью', **NULLABLE)
    blog_slug = models.CharField(max_length=150, verbose_name='slug', **NULLABLE)
    blog_date_creation = models.DateField(auto_now=False, auto_now_add=True, verbose_name='Дата создания')
    blog_is_active = models.BooleanField(default=True, verbose_name='Опубликовано')
    blog_views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, verbose_name='владелец', **NULLABLE)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.blog_title}'

    class Meta:
        verbose_name = 'Статья'  # Настройка для наименования одного объекта
        verbose_name_plural = 'Статьи'  # Настройка для наименования набора объектов
        ordering = ('blog_title',)  # сортировка по наименованию

catalog/views.py
from django.conf import settings
from django.contrib.auth import models
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.forms import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from pytils.translit import slugify
from django.core.cache import cache

import catalog
from catalog.forms import ProductForm, BlogForm, VersionForm, ProductModeratorForm
from catalog.models import Product, Blog, Version
from catalog.services import get_product_categories


def index(request):

    return render(request, 'catalog/home.html')


def contact(request):
    """
    Получает контактные данные, котрые клиент вносит при регистрации
    """

    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')
        print(f'Новое сообщение от {name}({phone}): {message}')

    # задаем контекстный параметр для вывода на страницу
    context = {
        'title': 'Контакты'
    }

    return render(request, 'catalog/contacts.html', context)


class ProductListView(ListView):
    """
    Выводит информаццию о последних 6 товарах на главную страницу
    """

    model = Product
    # queryset = Product.objects.all().order_by('-pk')[:6]  # получаем 6 последних товаров

    template_name = 'catalog/home.html'

    def get_queryset(self):

        user = self.request.user

        if user.is_authenticated:  # для зарегистрированных пользователей
            if user.is_staff or user.is_superuser:  # для работников и суперпользователя
                queryset = super().get_queryset().order_by('-pk')[:6]

            else:  # для остальных пользователей
                queryset = super().get_queryset().filter(
                    is_active=True).order_by('-pk')[:6]
        else:  # для незарегистрированных пользователей
            queryset = super().get_queryset().filter(
                is_active=True).order_by('-pk')[:6]
        return queryset

    # def get_queryset(self, *args, **kwargs):
    #     """
    #     Выводит в список только товары конкретного пользователя,
    #     либо если пользователь не авторизован - выводит все товары
    #     """
    #     queryset = super().get_queryset(*args, **kwargs)
    #
    #     try:
    #         queryset = queryset.filter(owner=self.request.user)
    #
    #     except TypeError:
    #         queryset = queryset.all().order_by('-pk')[:5]  # выводит последние 5 товаров
    #
    #     return queryset

# --------------------- рабочая версия ---------------------------
    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super(ProductListView, self).get_context_data(**kwargs)

        for product in context['product_list']:
            active_version = Version.objects.filter(product=product, is_active=True).last()
            if active_version:
                product.active_version_number = active_version.version_number
                product.active_version_name = active_version.version_name
            else:
                product.active_version_number = None
                product.active_version_name = None

        context['title'] = 'Главная'
        context['title_2'] = 'лучшие товары для вас'

        return context
# # ----------------------------------------------------------------

    # def get_context_data(self, **kwargs):
    #     """
    #     Выводит контекстную информацию в шаблон
    #     """
    #     context = super().get_context_data(**kwargs)
    #
    #     for product in context['product_list']:
    #
    #         if settings.CACHE_ENABLED:
    #             key = 'version_list'
    #             active_version = cache.get(key)
    #
    #             if active_version is None:
    #                 active_version = Version.objects.filter(product=product, is_active=True).last()
    #                 cache.set(key, active_version)
    #
    #             product.active_version_number = active_version.version_number
    #             product.active_version_name = active_version.version_name
    #
    #         else:
    #             active_version = Version.objects.filter(product=product, is_active=True).last()
    #
    #             product.active_version_number = active_version.version_number
    #             product.active_version_name = active_version.version_name
    #
    #     context['title'] = 'Главная'
    #     context['title_2'] = 'лучшие товары для вас'
    #
    #     return context


class ProductDetailView(DetailView):
    """
    Выводит информаццию об одном, выбранном на главной странице, товаре вместо функции product
    """
    model = Product
    # template_name = 'catalog/product_detail.html'

# --------------------- версия без кэширования ------------------------
    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context = super().get_context_data(**kwargs)

        active_version = Version.objects.filter(product=self.object, is_active=True).last()
        if active_version:
            context['active_version_number'] = active_version.version_number
            context['active_version_name'] = active_version.version_name
        else:
            context['active_version_number'] = None
            context['active_version_name'] = None

        context['title'] = 'Карточка товара'

        return context

# --------------------- версия с кэшированием --------------------------
#     def get_context_data(self, **kwargs):
#         """
#         Выводит контекстную информацию в шаблон
#         """
#         context = super().get_context_data(**kwargs)
#
#         version_is_active = self.object.version_set.filter(is_active=True).last()
#
#         if version_is_active:  # проверяем наличие версий
#
#             if settings.CACHE_ENABLED:
#                 key = 'active_version'  # ключ, по которому получаем список версий
#                 active_version = cache.get(key)  # получаем астивную версию
#
#                 if active_version is None:
#                     # проверяем кэш, если пусто, получаем данные из БД
#                     active_version = self.object.version_set.filter(is_active=True).last()
#
#                     cache.set(key, active_version)  # кэшируем активную версию
#
#             else:
#                 active_version = self.object.version_set.filter(is_active=True).last()
#
#             context['active_version_number'] = active_version.version_number
#             context['active_version_name'] = active_version.version_name
#
#         context['title'] = 'Карточка товара'
#
#         return context


class ProductCreateView(CreateView):
    """
    Выводит форму создания продукта
    """
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy('catalog:home')

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context_data = super().get_context_data(**kwargs)

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        formset = self.get_context_data()['formset']
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductUpdateView(UpdateView):
    """
    Выводит форму редактирования товара
    """
    model = Product
    form_class = ProductForm

    success_url = reverse_lazy('catalog:home')

    def get_form_class(self):
        product = self.get_object()
        user = self.request.user

        if user.is_staff:  # проверяем права доступа
            return ProductModeratorForm  # если модератор, то выводится отдельная форма

        elif product.owner == user:
            return ProductForm

        return super().get_form_class()

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """
        context_data = super().get_context_data(**kwargs)

        try:
            active_version = Version.objects.filter(product=self.object, is_active=True).last()

            # active_version_number = active_version.version_number

        except AttributeError:
            pass

        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)

        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = VersionFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        """
        Проверяем данные на правильность заполнения
        """
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class BlogListView(ListView):
    """
    Выводит информаццию о статьях блога
    """

    model = Blog
    template_name = 'catalog/blog_list.html'

    def get_context_data(self, **kwargs):
        """
        Выводит контекстную информацию в шаблон
        """

catalog/templates/catalog/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">{{ title_2 }}</p>
</div>

<div class="col-12">
    <div class="row">
        {% block content_1 %}
        {% endblock %}
    </div>
</div>
<br>

<div class="container">

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% include 'catalog/includes/inc_catalog_bottom.html' %}

</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/blog_confirm_delete.html
{% extends 'catalog/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            <p>Хотите удалить {{ object.blog_title }} ({{ object.blog_slug }}) ?</p>
                            <button type="submit" class="btn btn-danger">Подтвердить</button>
                            <a class="btn btn-warning" href="{% url 'catalog:blog_list' %}">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_detail.html
{% extends 'catalog/base.html' %}

{% block content %}

<div class="col-12">
    <div class="card shadow-sm">
        <div class="card-body bg-secondary mb-3">
            <p class="text-white">Статья - {{ object.blog_title }} ({{ object.blog_slug }})</p>
            <div class="card shadow-sm">
                <p class="card-text-dark">{{ object.blog_text }}</p>
            </div>
            <br>
            <div class="d-flex justify-content-between align-items-center">
                <div class="card shadow-sm">
                    <div class="btn-group">
                        {% if request.user == blog.owner %}
                        <a type="button" class="btn btn-sm btn-outline-secondary"
                           href="{% url 'catalog:edit_article' pk=object.id %}">Edit</a>
                        <a type="button" class="btn btn-sm btn-outline-danger"
                           href="{% url 'catalog:delete_article' pk=object.id %}">Delete</a>
                        {% endif %}
                    </div>
                </div>

            </div>
            <small class="text-white">Количество просмотров - {{ blog.blog_views_count }}</small><br>
            <small class="text-white">Дата создания - {{ blog.blog_date_creation }}</small>
        </div>
    </div>
</div>
<div class="col-12">
    {% if object.blog_preview %}
    <img src="/media/{{ object.blog_preview }}"/>
    {% else %}
    <img src="/media/catalog/no-image.jpg"/>
    {% endif %}
</div>

{% endblock %}

catalog/templates/catalog/blog_form.html
{% extends 'catalog/base.html' %}

{% block content %}

    <div class="col">
        <div class="row">
            <div class="col">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">
                                {% if object %}
                                Изменить
                                {% else %}
                                Создать
                                {% endif %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

catalog/templates/catalog/blog_list.html
{% extends 'catalog/base.html' %}

{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
    <p class="lead">Skystore - полезные статьи</p>
</div>

{% block content_1 %}

<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_article' %}">Написать статью</a>
    </div>
</div>

{% endblock %}

{% block content %}

{% for object in object_list %}

<div class="col-4">
    <div class="card shadow-sm">
        <div class="card-body">
            <p class="card-text">Статья: {{ object.blog_title }} ({{ object.blog_slug }})</p>
            <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                    <a type="button" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'catalog:blog_article' pk=object.id %}">View</a>
                    {% if perms.catalog.change_blog %}
                    <a type="button" class="btn btn-sm btn-outline-secondary"
                       href="{% url 'catalog:edit_article' pk=object.id %}">Edit</a>
                    {% endif %}
                    {% if perms.catalog.delete_blog %}
                    <a type="button" class="btn btn-sm btn-outline-danger"
                       href="{% url 'catalog:delete_article' pk=object.id %}">Delete</a>
                    {% endif %}
                </div>
            </div>
            <br>
            <small class="text-body-secondary">Количество просмотров - {{ object.blog_views_count }}</small>
            <br>
            <small class="text-body-secondary">Владелец - {{ object.owner|default:"Не определен" }}</small>
        </div>
    </div>
</div>

{% endfor %}


{% endblock %}

catalog/templates/catalog/contacts.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea name="message" class="form-control" id="message" placeholder="Сообщение" required></textarea>
                        </div>
<!--                        <input type="submit">-->
                        <input type="submit" class="btn btn-lg btn-block btn-outline-primary" value="Отправить" />
                    </form>

                </div>
            </div>
        </div>
    </div>

    {% include 'catalog/includes/inc_catalog_bottom.html' %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/home.html
{% extends 'catalog/base.html' %}

{% block content_1 %}
<div class="row py-lg-2">
    <div class="col-lg-11 col-md-8 mx-auto">
        {% if user.is_authenticated %}
        <a class="btn btn-outline-primary" href="{% url 'catalog:create_product' %}">Создать товар</a>
        {% else %}
        <a class="btn btn-outline-primary">Создавать товары могут только зарегистрированные пользователи</a>
        {% endif %}
    </div>
</div>
{% endblock %}

{% block content %}

{% for product in product_list %}
<div class="col-2">
    <div class="card mb-4 box-shadow">
        <div class="card-header">
            <div class="card-header">
                <h6 class="my-0 font-weight-normal">{{ product.product_name }}</h6>
            </div>
        </div>
        <div class="card-body">
            <h2 class="card-title pricing-card-title">{{ product.product_price }}</h2>
            <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                <li>{{ product.product_description|truncatechars:100 }}</li>
            </ul>
            {% if product.active_version_number %}
            <small class="text-body-secondary">Текущая версия - {{ product.active_version_number }}</small>
            <br>
            <small class="text-body-secondary">Описание версии - {{ product.active_version_name }}</small>
            {% endif %}
            <br>
            <small class="text-body-secondary">Владелец - {{ product.owner|default:"Не определен" }}</small>
            <br>
            {% if request.user.is_staff %}
                {% if product.is_active %}
                <small class="text-success">Статус товара - Опубликован</small>
                {% else %}
                <small class="text-danger">Статус товара - На модерации</small>
                {% endif %}
            {% endif %}
            <br><br>
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product' pk=product.id %}">Купить</a>
            {% if request.user == product.owner or request.user.is_staff %}
            <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:edit_product' pk=product.id %}">Изменить</a>
            {% endif %}
        </div>
    </div>
</div>
{% endfor %}

{% endblock %}

catalog/templates/catalog/product.html
{% load my_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore - {{ title }}</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
{% include 'catalog/includes/inc_catalog_menu.html' %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ title }}</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-5">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <div class="card-header">
                        <h6 class="my-0 font-weight-normal">{{ product.product_name }}</h6>
                    </div>
                </div>
                <div class="card-body">
                    <h2 class="card-title pricing-card-title">{{ product.product_price }}</h2>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>{{ product.product_description }}</li>
                    </ul>
                    <a class="p-2 btn btn-outline-primary">Купить</a>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="card-md-4">
                <div class="card-header">
                    <img class="card-img-top"
                         src="{{ product.product_preview|my_media }}"
                        alt="Card image cap" >

                </div>
            </div>
        </div>


    </div>

    {% include 'catalog/includes/inc_catalog_bottom.html' %}
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html' %}

{% block content %}


<div class="col-6">
    <form method="post" enctype="multipart/form-data">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">
                    {% if object %}
                    Редактирование товара
                    {% else %}
                    Добавление товара
                    {% endif %}
                </h4>
            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
            </div>
        </div>
        <br>
        <div class="col-6">
            <div class="card-body">
                {% if perms.catalog.change_product %}
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                    {{ form.as_p }}
                    {% if not forloop.last %}
                    <hr>
                    {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
        </div>

    </form>
</div>

{% endblock %}